"""Update Products model

Revision ID: 26c3b037ed58
Revises: e744f72ff967
Create Date: 2025-06-26 12:29:40.166684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c3b037ed58'
down_revision: Union[str, Sequence[str], None] = 'e744f72ff967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_grades', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('total_grades', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_grades')
    op.drop_column('products', 'quantity_grades')
    # ### end Alembic commands ###
